
# For sugar automated builds
ONBUILD ENV NODE_ENV=production
ONBUILD ADD . /app
ONBUILD RUN \
    echo ""                                                                     && \
    echo "# Welcome to cusspvz/node onbuild!"                                   && \
    echo ""                                                                     && \
    echo "Here are a few notes you must know:"                                  && \
    echo " - preinstall script: Set preinstall script on your package.json