
# For sugar automated builds
ONBUILD ENV NODE_ENV=production
ONBUILD ADD . /app
ONBUILD RUN \
    echo ""                                                                     && \
    echo "# Welcome to cusspvz/node onbuild!"                                   && \
    echo ""                                                   