FROM alpine:3.4
MAINTAINER José Moreira <jose.moreira@findhit.com>

ENV NODE_PREFIX=/usr/local \
    NODE_VERSION=latest \
    NPM_VERSION=latest \
    YARN_VERSION=latest \
    NODE_SOURCE=/usr/src/node \
    BASE_APKS="bash libgcc libstdc++ openssl ca-certificates" \
    BUILD_APKS="git curl wget bzip2 tar make gcc clang g+