
# development image specially created for builds
# This should include all resources for a node-based project such as:
# - build utils
# - docker so we can build a docker image on CI
# - versioning software

# Stuff that could be gathered through alpine package manager
RUN rm -f /etc/apk