#!/bin/bash

if [ "$1" == "" ] || \
   [ "$1" == "node" ];
   then
    exec $NODE_PREFIX/bin/node ${@:2}
    exit $?
fi

if [ "$1" == "start" ]; then
    cd /app
    exec $NODE_PREFIX/bin/npm start
    exit $?
fi

if [ "$1" == "test" ]; then
    cd /app
    exec $NODE_PREFIX/bin/npm test
    exit $?
fi

if [ "$1" == "ping" ]; then
    cd /app
    exec $NODE_PREFIX/bin/node -e "console.log('pong')"
    exit $?
fi

if [ "$1" == "shell" ] || \
   [